<?php //echo $this->getLayout()
//    ->createBlock("Magento\Reports\Block\Product\Widget\Viewed")
//    ->setDisplayType("recently.view.products")
//    ->setPageSize("4")->setTemplate("Knot_PreviousTabPDP::widget/viewed/content/viewed_grid.phtml")->toHtml();
//; ?>
<?php echo $this->getLayout()
    ->createBlock("Magento\Reports\Block\Product\Widget\Viewed")
    ->setDisplayType("recently.view.products")
    ->setPageSize("4")
    ->setTemplate("Knot_PreviousTabPDP::widget/viewed/content/viewed_grid.phtml")
    ->toHtml();
; ?>
